import asyncio
import logging
import os
from typing import Optional

from integrations.fhir_client import FHIRClient, FHIRError
from integrations.llm_client import LLMClient
from models.lab import AbnormalLab
from models.medication import MedicationEntry
from models.deterioration import DeteriorationReport
from sharp import (
    extract_sharp_context,
    resolve_patient_id,
    build_sharp_metadata,
    role_is,
    log_tool_call,
    log_sharp_absent,
)
from evidence.trail import build_cross_domain_evidence
from persona.adapter import PersonaAdapter
from memory.store import pattern_memory
from memory.signature import pattern_signature

logger = logging.getLogger(__name__)

fhir = FHIRClient()
llm = LLMClient()
persona = PersonaAdapter(llm)

DISCLAIMER = (
    "This synthesis is generated by an AI clinical decision support tool for informational "
    "purposes only. It does not constitute a diagnosis, clinical recommendation, or prescription. "
    "All clinical decisions must be made by a qualified healthcare professional."
)


def _format_labs_for_prompt(labs: list[dict]) -> str:
    if not labs:
        return "No recent abnormal labs."
    lines = []
    for lab in labs[:8]:
        name = lab.get("display_name", "Unknown")
        val = lab.get("value") or lab.get("value_string", "N/A")
        unit = lab.get("unit") or ""
        ref = lab.get("reference_range", "")
        level = lab.get("abnormality_level", "")
        trend_obj = lab.get("trend") or {}
        trend = trend_obj.get("direction", "unknown") if trend_obj else "unknown"
        lines.append(f"  - {name}: {val} {unit} (ref: {ref}, level: {level}, trend: {trend})")
    return "\n".join(lines)


def _format_meds_for_prompt(meds: list[dict]) -> str:
    if not meds:
        return "No recent medications."
    lines = []
    for med in meds[:10]:
        name = med.get("display_name", "Unknown")
        status = med.get("status", "")
        date = med.get("authored_on", "unknown date")
        flags = med.get("interaction_flags", [])
        flag_str = f" [INTERACTION: {len(flags)} flag(s)]" if flags else ""
        lines.append(f"  - {name} ({status}, started {date}){flag_str}")
    return "\n".join(lines)


def _format_vitals_for_prompt(deterioration: dict) -> str:
    news2 = deterioration.get("news2") or {}
    mews = deterioration.get("mews") or {}
    risk = deterioration.get("risk_level", "unknown")
    rules = deterioration.get("triggered_rules", [])
    latest = deterioration.get("latest_vitals") or {}

    lines = [
        f"  NEWS2 score: {news2.get('total_score', 'N/A')} ({news2.get('risk_level', 'N/A')} risk)",
        f"  MEWS score: {mews.get('total_score', 'N/A')} ({mews.get('risk_level', 'N/A')} risk)",
        f"  Overall risk: {risk}",
    ]
    if latest:
        for k, v in latest.items():
            lines.append(f"  {k.replace('_', ' ').title()}: {v}")
    if rules:
        lines.append(f"  Triggered rules: {'; '.join(rules[:5])}")
    return "\n".join(lines)


def _build_synthesis_prompt(
    clinical_question: str,
    labs_text: str,
    meds_text: str,
    vitals_text: str,
    role: str,
) -> str:
    role_instruction = {
        "nurse": (
            "You are addressing a nurse. Provide an actionable summary focused on what to monitor "
            "and report. Use clear, plain language. Avoid complex diagnostic terminology."
        ),
        "pharmacist": (
            "You are addressing a pharmacist. Focus on medication-related patterns, drug interactions, "
            "and how the lab/vital trends relate to the current drug regimen."
        ),
        "physician": (
            "You are addressing a physician. Provide full clinical reasoning with appropriate "
            "medical terminology. Include differential considerations without diagnosing."
        ),
    }.get(role.lower() if role else "", (
        "You are addressing a clinician. Provide a balanced clinical synthesis."
    ))

    return f"""You are a clinical decision support AI. Your role is to synthesize patient data
and help clinicians think through a clinical question.

STRICT RULES:
- Do NOT diagnose. Do NOT use the words "diagnosis" or "diagnose".
- Do NOT prescribe or recommend specific medications.
- Do NOT use the word "prescribe".
- Use language like "may suggest", "warrants evaluation for", "is consistent with", "clinician should assess".
- Always acknowledge uncertainty and data limitations.
- End your response with: "Action required by: clinician."

{role_instruction}

CLINICAL QUESTION:
{clinical_question}

RECENT ABNORMAL LABS (last 30 days):
{labs_text}

CURRENT MEDICATIONS (last 90 days):
{meds_text}

VITAL SIGNS / DETERIORATION SIGNALS (last 72 hours):
{vitals_text}

Provide a synthesis narrative (3-5 sentences) that:
1. Directly addresses the clinical question using the data above
2. Identifies cross-domain patterns (e.g., lab trend + medication timing + vital signs together)
3. Notes what data is missing or uncertain
4. States your confidence level (low/moderate/high) and why

Respond in this exact JSON format:
{{
  "synthesis_narrative": "...",
  "confidence_level": "low|moderate|high",
  "confidence_reasoning": "...",
  "data_gaps": ["...", "..."],
  "cross_domain_patterns": ["...", "..."]
}}"""


async def synthesize_cross_domain_insights(
    patient_id: str,
    clinical_question: str,
    role: str = None,
    ctx=None,
) -> dict:
    """
    Synthesize cross-domain clinical insights by combining lab trends, medication history,
    and vital sign patterns to answer a specific clinical question.

    This tool calls get_recent_abnormal_labs, get_medication_timeline, and
    detect_clinical_deterioration_signals in parallel, then uses AI to reason
    across all three domains simultaneously — something rule-based systems cannot do.

    Args:
        patient_id: FHIR Patient resource ID (overridden by SHARP context if present)
        clinical_question: Free-text clinical question (e.g. 'Is this patient safe for discharge?',
                           'What is driving the elevated creatinine?')
        role: Clinician role — "physician", "nurse", "pharmacist", or "patient". ALWAYS pass this to adapt output format.
        ctx: MCP context — carries SHARP headers from Prompt Opinion platform

    Returns:
        ClinicalInsight with synthesis_narrative, confidence_level, data_gaps,
        supporting_data counts, action_required_by='clinician', and sharp_metadata.
        Always includes ai_generated=True and disclaimer.
    """
    sharp = extract_sharp_context(ctx, role_hint=role)
    effective_id = resolve_patient_id(patient_id, sharp)

    if sharp.is_present:
        log_tool_call("synthesize_cross_domain_insights", sharp.session_id, sharp.role)
    else:
        log_sharp_absent("synthesize_cross_domain_insights")

    if not effective_id:
        return {"error": "MISSING_PATIENT_ID", "message": "patient_id required", "retry_suggested": False}

    if not clinical_question or not clinical_question.strip():
        return {
            "error": "MISSING_CLINICAL_QUESTION",
            "message": "clinical_question is required",
            "retry_suggested": False,
        }

    import tools.lab_results as _lab_mod
    import tools.medications as _med_mod
    import tools.deterioration as _det_mod

    labs_result, meds_result, deterioration_result = await asyncio.gather(
        _lab_mod.get_recent_abnormal_labs(effective_id, days=30, threshold="borderline", ctx=ctx),
        _med_mod.get_medication_timeline(effective_id, days=90, ctx=ctx),
        _det_mod.detect_clinical_deterioration_signals(effective_id, hours_lookback=72, ctx=ctx),
        return_exceptions=True,
    )

    labs_data: list[dict] = []
    meds_data: list[dict] = []
    det_data: dict = {}
    sub_errors: list[str] = []

    if isinstance(labs_result, Exception) or labs_result.get("error"):
        sub_errors.append("Lab results unavailable")
    else:
        labs_data = labs_result.get("abnormal_labs", [])

    if isinstance(meds_result, Exception) or meds_result.get("error"):
        sub_errors.append("Medication data unavailable")
    else:
        meds_data = meds_result.get("medications", [])

    if isinstance(deterioration_result, Exception) or deterioration_result.get("error"):
        sub_errors.append("Vital signs/deterioration data unavailable")
    else:
        det_data = deterioration_result

    labs_text = _format_labs_for_prompt(labs_data)
    meds_text = _format_meds_for_prompt(meds_data)
    vitals_text = _format_vitals_for_prompt(det_data) if det_data else "Vital signs data unavailable."

    role = sharp.role or "clinician"
    prompt = _build_synthesis_prompt(clinical_question, labs_text, meds_text, vitals_text, role)

    raw_response = await llm.synthesize(prompt)

    synthesis_narrative = None
    confidence_level = "low"
    confidence_reasoning = None
    data_gaps: list[str] = sub_errors.copy()
    cross_domain_patterns: list[str] = []

    if raw_response:
        import json as _json
        try:
            parsed = _json.loads(raw_response)
            synthesis_narrative = parsed.get("synthesis_narrative")
            confidence_level = parsed.get("confidence_level", "low")
            confidence_reasoning = parsed.get("confidence_reasoning")
            data_gaps += parsed.get("data_gaps", [])
            cross_domain_patterns = parsed.get("cross_domain_patterns", [])
        except (_json.JSONDecodeError, AttributeError):
            synthesis_narrative = raw_response

    # Build evidence trail from the three domains of data
    latest_vitals = det_data.get("latest_vitals") or {} if det_data else {}
    evidence = build_cross_domain_evidence(
        labs=labs_data,
        meds=meds_data,
        vitals=latest_vitals,
        lab_recency_hours=24.0,
        med_recency_hours=72.0,
        vital_recency_hours=12.0,
    )

    # Auto-record pattern to Clinical Pattern Memory (non-blocking, never errors main flow)
    if os.getenv("PATTERN_MEMORY_ENABLED", "true").lower() == "true":
        try:
            conditions = pattern_signature.from_synthesis_context(
                labs=labs_data,
                meds=meds_data,
                vitals_summary={"risk_level": det_data.get("risk_level", "")} if det_data else {},
            )
            if conditions:
                outcome = "cross_domain_concern" if confidence_level != "low" else "monitoring"
                pattern_memory.record(conditions, outcome)
        except Exception:
            pass  # Pattern recording must never block or crash main flow

    result = {
        "patient_id": effective_id,
        "clinical_question": clinical_question,
        "synthesis_narrative": synthesis_narrative,
        "confidence_level": confidence_level,
        "confidence_reasoning": confidence_reasoning,
        "data_gaps": data_gaps,
        "cross_domain_patterns": cross_domain_patterns,
        "supporting_data": {
            "labs_referenced": len(labs_data),
            "medications_referenced": len(meds_data),
            "vitals_referenced": det_data.get("vital_signs_count", 0),
            "news2_score": (det_data.get("news2") or {}).get("total_score"),
            "overall_risk": det_data.get("risk_level"),
        },
        "evidence_trail": evidence.model_dump(),
        "action_required_by": "clinician",
        "ai_generated": True,
        "disclaimer": DISCLAIMER,
        "sharp_metadata": build_sharp_metadata(sharp),
    }
    if sharp.role:
        result = await persona.adapt(result, sharp.role)
    else:
        result["persona_applied"] = "physician"
    return result
